import { redirect } from "next/navigation";
import { prisma } from "@/lib/db";
import { can, currentRole } from "@/lib/session";
import { isGeminiConfigured } from "@/lib/ai/gemini";
import { isEmailConfigured } from "@/lib/ai/email";
import { ReportClient, type ReportRow } from "./ReportClient";

export const dynamic = "force-dynamic";

function toRow(r: {
  id: string;
  kind: string;
  scopeKey: string;
  title: string;
  body: string;
  model: string | null;
  tokensIn: number | null;
  tokensOut: number | null;
  generatedAt: Date;
  emailedAt: Date | null;
  emailedTo: string | null;
}): ReportRow {
  return {
    id: r.id,
    kind: r.kind,
    scopeKey: r.scopeKey,
    title: r.title,
    body: r.body,
    model: r.model,
    tokensIn: r.tokensIn,
    tokensOut: r.tokensOut,
    generatedAt: r.generatedAt.toISOString(),
    emailedAt: r.emailedAt?.toISOString() ?? null,
    emailedTo: r.emailedTo,
  };
}

export default async function ReportsPage() {
  const role = await currentRole();
  if (!can(role, "report:view")) redirect("/");

  const reports = await prisma.aiReport.findMany({
    orderBy: { generatedAt: "desc" },
  });

  return (
    <div className="space-y-5 max-w-3xl mx-auto w-full">
      <div>
        <h1 className="text-xl font-semibold">AI reports</h1>
        <p className="text-xs text-ink-faint mt-1 max-w-xl">
          Plain-English narratives generated by Gemini from BroMonitor data.
          Weekly (auto-runnable every Sunday), monthly synthesis, and pre-test
          briefs. Emailed if SMTP is set up.
        </p>
      </div>

      <ReportClient
        weekly={reports.filter((r) => r.kind === "weekly").map(toRow)}
        monthly={reports.filter((r) => r.kind === "monthly").map(toRow)}
        testBriefs={reports.filter((r) => r.kind === "test_brief").map(toRow)}
        geminiConfigured={isGeminiConfigured()}
        emailConfigured={isEmailConfigured()}
        canDelete={can(role, "report:delete")}
      />
    </div>
  );
}
